path: .
jobs: 10
extensions:
  - php
exclude:
  - .github
  - .vscode
  - .idea
  - tests
  - tests-old
  - .wordpress-org
  - bin
  - vendor
  - dist
  - languages
  - node_modules
  - dev-workspace
  - cache
  - .cache
  - assets
