[{
    "caption": "ajax",
    "value": 2346
}, {
    "caption": "beth",
    "value": 3126
}, {
    "caption": "blog",
    "value": 23
}, {
    "caption": "calendar",
    "value": 367
}, {
    "caption": "calendar entries",
    "slug": "calendar-entries",
    "value": 21
}, {
    "caption": "Collaboration University",
    "slug": "collaboration-university",
    "value": 1467
}, {
    "caption": "JavaScript",
    "value": 1173
}, {
    "caption": "demo",
    "value": 6234
}, {
    "caption": "Prototype",
    "value": 3178
}, {
    "caption": "domino",
    "value": 2023
}, {
    "caption": "family",
    "value": 945
}, {
    "caption": "google",
    "value": 283
}, {
    "caption": "ibm",
    "value": 5946
}, {
    "caption": "lotusphere",
    "value": 1124
}, {
    "caption": "lotus quickr",
    "slug": "lotus-quickr",
    "value": 2796
}, {
    "caption": "movies",
    "value": 223
}, {
    "caption": "podcast",
    "value": 3864
}, {
    "caption": "snapps",
    "value": 3024
}, {
    "caption": "templates",
    "value": 1735
}, {
    "caption": "tutorial",
    "value": 1183
}, {
    "caption": "widget",
    "value": 4235
}, {
    "caption": "xhr",
    "value": 322
}]
